version: "3.6"
services:
  restapi:
    image: labelspeech_backend
    build: backend/.
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    entrypoint: ["python3", "main.py"]
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=labelspeech_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=s3_secret_key
    restart: always
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  nginx:
    image: label_nginx
    build: frontend/
    hostname: "labelspeech.your.address"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/public
